# Generated by Django 4.2.29 on 2026-04-15 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon", models.CharField(default="📁", max_length=10)),
                ("color", models.CharField(default="#6366f1", max_length=20)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("stack", models.CharField(blank=True, max_length=300)),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("idea", "Idea"),
                            ("mvp", "MVP"),
                            ("startup", "Startup"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sphere",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fintech", "Fintech"),
                            ("edtech", "EdTech"),
                            ("gamedev", "GameDev"),
                            ("healthcare", "Healthcare"),
                            ("ecommerce", "E-Commerce"),
                            ("social", "Social"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("preferred_time", models.CharField(blank=True, max_length=100)),
                (
                    "experience_required",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("middle", "Middle"),
                            ("senior", "Senior"),
                            ("any", "Any"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("likes_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="posts.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="posts.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "post")},
            },
        ),
    ]
